import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ClerkProvider, SignedIn } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";
import { Menu } from "@/components/Menu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <head>
          <meta name="application-name" content="Finance Sync" />
          <meta name="apple-mobile-web-app-capable" content="yes" />
          <meta
            name="apple-mobile-web-app-status-bar-style"
            content="default"
          />
          <meta name="apple-mobile-web-app-title" content="Finance Sync" />
          <meta
            name="description"
            content="Time to finally sort out all your finances"
          />
          <meta name="format-detection" content="telephone=no" />
          <meta name="mobile-web-app-capable" content="yes" />
          <meta
            name="msapplication-config"
            content="/icons/browserconfig.xml"
          />
          <meta name="msapplication-TileColor" content="#2B5797" />
          <meta name="msapplication-tap-highlight" content="no" />
          <meta name="theme-color" content="#000000" />
          <link rel="manifest" href="/manifest.json" />
        </head>
        <body className={cn(inter.className, "bg-slate-100")}>
          <SignedIn>
            <header className="fixed top-0 left-0 right-0 z-50 bg-background border-b p-4">
              <div className="container mx-auto flex justify-between items-center">
                <Menu />
                <h1 className="text-xl font-bold">Yet Another Finance App</h1>
              </div>
            </header>
          </SignedIn>
          <main className="pt-12">{children}</main>
        </body>
        <Toaster />
      </html>
    </ClerkProvider>
  );
}
